#################################################
# DO Community Playbooks: Initial Server Setup
#################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

# Sudo Group Setup
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

# User + Key Setup
    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ create_user }}"
        state: present
        groups: wheel
        append: true
        create_home: true
        shell: /bin/bash

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ copy_local_key }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: Disable password authentication in general
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Change SSH port
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?Port'
        line: 'Port {{ ssh_port }}'

# Install Packages
    - name: Update apt
      apt: update_cache=yes

    - name: Install required system packages
      apt: name={{ sys_packages }} state=latest

# UFW Setup
    - name: UFW - Allow SSH connections on a custom port
      ufw:
        rule: allow
        port: '{{ ssh_port }}'
        proto: tcp
    - name: UFW - Limit the number of possible requests
      ufw:
        rule: limit
        port: '{{ ssh_port }}'
        proto: tcp
    - name: UFW - Allow HTTP connections
      ufw:
        rule: allow
        port: '80'
        proto: tcp
    - name: UFW - Allow HTTPS connections
      ufw:
        rule: allow
        port: '443'
        proto: tcp

    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Restart sshd
      service:
        name: sshd
        state: restarted

# Unattended Upgrades
    - name: Install unattended-upgrades package
      apt:
        name: "unattended-upgrades"
        state: present

    - name: Create apt auto-upgrades configuration
      template:
        src: files/20auto-upgrades.j2
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        owner: root
        group: root
        mode: 0644

    - name: Create apt unattended-upgrades configuration
      template:
        src: files/50unattended-upgrades.j2
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        owner: root
        group: root
        mode: 0644