---
create_user: lukas
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/keys/hetzner_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw']
ssh_port: 4018
unattended_upgrade_error_mail: unatt-upgr@lukaszanner.de
